// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFLWeeklyPicksAPI;

#nullable disable

namespace NFLWeeklyPicksAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220813181028_initial-create-picks")]
    partial class initialcreatepicks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NFLWeeklyPicksAPI.Models.Entities.PickTypes", b =>
                {
                    b.Property<int>("PickTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PickTypeId"), 1L, 1);

                    b.Property<int>("PickType")
                        .HasColumnType("int");

                    b.HasKey("PickTypeId");

                    b.ToTable("PickTypes");
                });

            modelBuilder.Entity("NFLWeeklyPicksAPI.Models.Entities.UserPickLineItems", b =>
                {
                    b.Property<int>("UserPickLineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPickLineItemId"), 1L, 1);

                    b.Property<long>("CompetitionId")
                        .HasColumnType("bigint");

                    b.Property<int>("PickTeamId")
                        .HasColumnType("int");

                    b.Property<int>("PickTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserPickId")
                        .HasColumnType("int");

                    b.HasKey("UserPickLineItemId");

                    b.HasIndex("PickTypeId");

                    b.HasIndex("UserPickId");

                    b.ToTable("UserPickLineItems");
                });

            modelBuilder.Entity("NFLWeeklyPicksAPI.Models.Entities.UserPickPoints", b =>
                {
                    b.Property<int>("UserPickPointsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPickPointsId"), 1L, 1);

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("UserPickLineItemId")
                        .HasColumnType("int");

                    b.HasKey("UserPickPointsId");

                    b.HasIndex("UserPickLineItemId");

                    b.ToTable("UserPickPoints");
                });

            modelBuilder.Entity("NFLWeeklyPicksAPI.Models.Entities.UserPicks", b =>
                {
                    b.Property<int>("UserPicksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPicksId"), 1L, 1);

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Week")
                        .HasColumnType("int");

                    b.HasKey("UserPicksId");

                    b.ToTable("UserPicks");
                });

            modelBuilder.Entity("NFLWeeklyPicksAPI.Models.Entities.UserPickLineItems", b =>
                {
                    b.HasOne("NFLWeeklyPicksAPI.Models.Entities.PickTypes", "PickType")
                        .WithMany()
                        .HasForeignKey("PickTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLWeeklyPicksAPI.Models.Entities.UserPicks", "UserPick")
                        .WithMany("PickLineItems")
                        .HasForeignKey("UserPickId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PickType");

                    b.Navigation("UserPick");
                });

            modelBuilder.Entity("NFLWeeklyPicksAPI.Models.Entities.UserPickPoints", b =>
                {
                    b.HasOne("NFLWeeklyPicksAPI.Models.Entities.UserPickLineItems", "UserPickLineItem")
                        .WithMany()
                        .HasForeignKey("UserPickLineItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserPickLineItem");
                });

            modelBuilder.Entity("NFLWeeklyPicksAPI.Models.Entities.UserPicks", b =>
                {
                    b.Navigation("PickLineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
